### ISSUE TITLE
Cookies list is not updated after deleting a cookie

### ISSUE THREAD

**Issue by alexdevero** [Privacy-Managers/Privacy-Manager#83]
The list of cookies is not updated after deleting some cookie on the list. It is updated only if I click on the cookie to see all cookies for that domain and only then I remove the domain/cookie.

In earlier version, cookies list was update every time cookie has been deleted. Now, it is necessary to close the extension pop-up and open it again to "refresh" the list.

Steps to reproduce:
1) Visit some website to store a new cookie
2) Open the extension pop-up and click the button to remove the cookie.
3) Observe that the list will not refresh and the cookies stays on the list, even though it no longer exists.

Browser: Vivaldi 2.10.1745.26 (built on Chrome 79.0.3945.118)

![Výstřižek](https://user-images.githubusercontent.com/4237724/72202500-8d478200-3460-11ea-97ee-1a0cc59e5793.PNG)

**Comment by Manvel** [comment]
@alexdevero Thanks for reporting the issue, I can confirm that the cookies for domain are not deleted unless list item is expanded.

Lately Privacy Manager went [through big rewrite](https://manvel.me/projects/privacy-manager/rewrite), it's a shame that the automation tests didn't fetch the case and I have missed that.

I'll have a closer look into what is causing the issue and come back to you with more details.

**Comment by alexdevero** [comment]
Thank you @Manvel.

**Comment by Manvel** [comment]
@alexdevero the issue [was caused by a blocking case](https://github.com/Privacy-Managers/Privacy-Manager/commit/612488e98f09edf38a5a319128b6951d17003ebe), which tried to ensure that item has subitems(is expanded) before removing from the UI and automated tests which suppose to fetch that error, were running on the expanded item.

Thanks again for noticing the issue, the [release is out](https://github.com/Privacy-Managers/Privacy-Manager/releases/tag/3.5.2) and [available in the Chrome Web Store](https://chrome.google.com/webstore/detail/privacy-manager/giccehglhacakcfemddmfhdkahamfcmd).

**Comment by alexdevero** [comment]
Can confirm that the fix works.
