### ISSUE TITLE
All cookies are not deleted by "Delete all"

### ISSUE THREAD

**Issue by alexdevero** [Privacy-Managers/Privacy-Manager#85]
All cookies shown on the list are not deleted when I click the "Delete all" button. This doesn't apply only to protected cookies, which should not be deleted. It applies to all cookies, including un-protected.

When I click the "Delete all" button some cookies are deleted and the list is updated. However, there are many cookies left. Further clicking on "Delete all" button does nothing.

Browser: Vivaldi (Chromium/Webkit-based)
Extension version: 3.5.2

**Comment by Manvel** [comment]
@alexdevero Thanks for reporting the issue.

That's indeed strange and not an expected behavior, unfortunately I'm not yet able to reproduce it on Vivaldi v `2.11.1811.47`.

Can you please confirm that:
- [ ]  The domain item and cookie items that are not deleted aren't whitelisted(doesn't have green whitelist icon set next to the "x" button)?
- [ ] Additional permission are enabled
- [ ] No error when inspecting the popup
  - Right click in extension popup -> Inspect -> Console
- [ ] No error when inspecting background page
  -  Right click on extension icon -> Manage extensions -> Set/ensure Developer mode "on" -> Details -> click "background page" in "Inspect views" -> Console
- [ ] Issue doesn't happen when other extensions are disabled
 
Hope to fix the issue ASAP as soon I know how to reproduce it.

**Comment by Manvel** [comment]
Hmm, I think I'm into something.. That's quite weird and embarrassing..

In some websites(ex.: booking.com) some cookies are being automatically whitelisted, I hope it's a bug in Privacy Manager and I can fix it. If that's true then if you expend domain item then you might see whitelisted cookies with green icon next to them. I'm not sure yet in which exact circumstances that happens.

Debugging now to confirm that case.

**Comment by Manvel** [comment]
Here is the issue https://github.com/Privacy-Managers/Privacy-Manager/blob/master/src/js/ui/tabs/cookies.js#L529 

The problem is that `setWhitelistCookie` doesn't take 3-rd parameter, unlike `setWhitelistDomain` it doesn't allow setting the state of the whitelist, hence `setWhitelistCookie` should be `toggleWhitelistCookie` to avoid confusion which leads to such mistake, or take 3-rd parameter accordingly.

So in the scenario when a page removes the cookie, `setWhitelistCookie` is being triggered naively hoping that program is cleaning whitelist accordingly, instead it toggle's sets whitelist.

I'll fix this issue soon.

**Comment by alexdevero** [comment]
Good job! You've figured it out before I had time to answer your questions above :).

**Comment by Manvel** [comment]
@alexdevero thanks again for reporting the issue(s).

The [release is out](https://github.com/Privacy-Managers/Privacy-Manager/releases/tag/3.5.3), but the extension is pending Chrome Web Store review, I'll let you know as soon the latest version is available in CWS.

As soon the new version of Privacy Manager is available again you can either reinstall the extension to remove the whitelist corruption or run the script below in the popup:

```
browser.storage.local.set({cookieWhitelist: {}});
```

I have added you to the [list of contributors](https://github.com/Privacy-Managers/Privacy-Manager#thanks-to-the-awesome-contributors), hope you don't mind(otherwise please let me know).

**Comment by alexdevero** [comment]
Thanks a lot for quick fix, and adding me as contributor. Next time, it will be code contribution.

**Comment by Manvel** [comment]
@alexdevero review passed and the latest version(3.5.3) should now be available at CWS.
